services:
  shortify-api:
    environment:
      Logging__LogLevel__Default: "Debug"
      Logging__LogLevel__Microsoft.AspNetCore: "Warning"
      Logging__LogLevel__Microsoft.EntityFrameworkCore: "Information"
